install.packages("proj4")
install.packages("caTools")
install.packages("bitops")
install.packages("ckanr")
install.packages("googledrive")
install.packages("fuzzyjoin")
install.packages("leaflet")
install.packages("leaflet")
install.packages("leaflet.extras")
install.packages("leaflet.providers")
install.packages("leaftime")
install.packages("listviewer")
install.packages("reactable")
install.packages("skimr")
install.packages("stringi")
install.packages("usethis")
install.packages("mapview")
install.packages("leafpop")
install.packages("leafem")
install.packages("lattice")
install.packages("sf")

RUN R -e "remotes::install_github('ropensci/ruODK@main', \
          dependencies = TRUE, ask=FALSE, update=TRUE)"
